#!/bin/sh

#scw=$(xrandr | grep \* | awk {'print $1'} | sed "s/x.*//")
#sch=$(xrandr | grep \* | awk {'print $1'} | sed "s/.*x//")
#wh=$(echo "$sch * 0.3" | bc -l | awk {'print int($1)'})
#wt=$(echo "($sch - $wh) * 1.2" | bc -l | awk {'print int($1)'})
#wl=$(echo "($scw - $wh) * 1.35" | bc -l | awk {'print int($1)'})

#pkill ffplay || ffplay -f video4linux2 -framerate 30  -y $wh -top $wt -left $wl -noborder -an -sn  -i /dev/video0

pkill ffplay || ffplay -f video4linux2 -framerate 30 -noborder -an -sn -x 720 -y 450 -top 930 -left 1750 -i /dev/video0
