#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch
emacs --daemon &
wallpaper &

bspc monitor DP-4 -d 6 7 8 9 0
bspc monitor DP-0 -d 1 2 3 4 5


bspc config border_radius                 15
bspc config border_width                  4
bspc config window_gap                    7
bspc config top_padding                   10
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.67
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


#### BSPWM coloring ####
bspc config normal_border_color		      	"#222222"
bspc config active_border_color	          	"#8a8d8f"
bspc config focused_border_color	      	"#00909e"
bspc config presel_feedback_color	      	"#ffa102"
bspc config urgent_border_color 	      	"#ac1d37"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
