#!/bin/sh

# Terminate already running bar instances
# If all your bars have ipc enabled, you can use 
polybar-msg cmd quit
# Otherwise you can use the nuclear option:
# killall -q polybar

# Launch bar1 and bar2
echo "---" | tee -a /tmp/polybar1.log /tmp/polybar2.log
polybar left1 2>&1 | tee -a /tmp/polybar1.log & disown
polybar monitor 2>&1 | tee -a /tmp/polybar1b.log & disown
polybar center1 2>&1 | tee -a /tmp/polybar2.log & disown
polybar right 2>&1 | tee -a /tmp/polybar3.log & disown
polybar left2 2>&1 | tee -a /tmp/polybar4.log & disown
polybar center2 2>&1 | tee -a /tmp/polybar5.log & disown
polybar right2 2>&1 | tee -a /tmp/polybar6.log & disown

echo "Bars launched..."
